// Generated by gencpp from file maplin_arm/MotorState.msg
// DO NOT EDIT!


#ifndef MAPLIN_ARM_MESSAGE_MOTORSTATE_H
#define MAPLIN_ARM_MESSAGE_MOTORSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maplin_arm
{
template <class ContainerAllocator>
struct MotorState_
{
  typedef MotorState_<ContainerAllocator> Type;

  MotorState_()
    : motorIdx(0)
    , motorState(0)  {
    }
  MotorState_(const ContainerAllocator& _alloc)
    : motorIdx(0)
    , motorState(0)  {
  (void)_alloc;
    }



   typedef int32_t _motorIdx_type;
  _motorIdx_type motorIdx;

   typedef int32_t _motorState_type;
  _motorState_type motorState;





  typedef boost::shared_ptr< ::maplin_arm::MotorState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maplin_arm::MotorState_<ContainerAllocator> const> ConstPtr;

}; // struct MotorState_

typedef ::maplin_arm::MotorState_<std::allocator<void> > MotorState;

typedef boost::shared_ptr< ::maplin_arm::MotorState > MotorStatePtr;
typedef boost::shared_ptr< ::maplin_arm::MotorState const> MotorStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maplin_arm::MotorState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maplin_arm::MotorState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace maplin_arm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'maplin_arm': ['/home/roshenac/Desktop/makeitmove/src/maplin_arm/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::maplin_arm::MotorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maplin_arm::MotorState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maplin_arm::MotorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maplin_arm::MotorState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maplin_arm::MotorState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maplin_arm::MotorState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maplin_arm::MotorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1bf503c86341bd1bc89b93762b377cea";
  }

  static const char* value(const ::maplin_arm::MotorState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1bf503c86341bd1bULL;
  static const uint64_t static_value2 = 0xc89b93762b377ceaULL;
};

template<class ContainerAllocator>
struct DataType< ::maplin_arm::MotorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maplin_arm/MotorState";
  }

  static const char* value(const ::maplin_arm::MotorState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maplin_arm::MotorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 motorIdx\n\
int32 motorState\n\
";
  }

  static const char* value(const ::maplin_arm::MotorState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maplin_arm::MotorState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motorIdx);
      stream.next(m.motorState);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maplin_arm::MotorState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maplin_arm::MotorState_<ContainerAllocator>& v)
  {
    s << indent << "motorIdx: ";
    Printer<int32_t>::stream(s, indent + "  ", v.motorIdx);
    s << indent << "motorState: ";
    Printer<int32_t>::stream(s, indent + "  ", v.motorState);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAPLIN_ARM_MESSAGE_MOTORSTATE_H
